### ISSUE TITLE
Writing results to different file types?

### ISSUE THREAD

**Issue by AHaumer** [modelica-3rdparty/ExternData#38] opened 2021-06-29 18:04 UTC
As far as I see, ExternData is an excellent tool to read parameters from different data sources.
Are there plans - or do you know a tool - to write results (at the end of a simulation) to different file types?
This would offer opportunities for some more applications ...

**Comment by tbeu** [comment] 2021-06-29 18:51
Looks like a duplicate of #8 to me. Currently there are no plans to write simulation results to files. This should be up to the tools.

**Comment by beutlich** [comment] 2021-07-18 13:18
My recommended workaround is to store the simulation result data as CSV file, which then can be read again by the 1D look-up table blocks of [ModelicaTableAdditions](https://github.com/tbeu/ModelicaTableAdditions).

**Closed as completed by beutlich** 2021-07-18 13:18 UTC
Labels: wontfix
