### ISSUE TITLE
Missing ModelicaExternalC.dll in Modelica

### ISSUE THREAD

**Issue by jnangle** [modelica-3rdparty/ExternData#2] opened 2015-07-29 20:38 UTC
I was excited to see this code available, however I get the following error when I load the Modelica code into Dymola and run a simulation on the XMLTest1 model:

The program can't start because ModelicaExternalC.dll is missing from your computer.  Try reinstalling the program to fix this problem.

I can find ModelicaExternalC.lib, but not the dynamic library.  Do I need to to change something in the ExternData code in order for it to look for the static library, not the dynamic library?

System specifics:
Windows 7 Enterprise SP1
Dymola 2015 and 2016 32-bit and 64-bit versions

**Comment by tbeu** [comment] 2015-07-29 21:32
The library should work out-of-the-box with Dymola. ModelicaExternalC.dll (and in fact all DLLs) is not required by Dymola. Only ED_XMLFile.lib and expat.lib from the library and ModelicaExternalC.lib from the Dymola installation are needed for linking an executable of XMLTest1.

**Comment by jnangle** [comment] 2015-07-29 21:38
That's what I thought should happen.  However, I get the error message above when I use version 1.0.2 of ExternData.

**Comment by tbeu** [comment] 2015-07-29 21:47
Did you open package.mo in Dymola? What happens if you delete all DLLs from the Library dirs?

**Comment by tbeu** [comment] 2015-07-29 21:51
You must not use ExternData\Resources\thirdParty\ITI\win32\ModelicaExternalC.lib with Dymola. This is only for building the DLLs for SimulationX from ITI. Dymola provides its own ModelicaExternalC.lib.

**Comment by jnangle** [comment] 2015-07-29 21:57
Deleting all of the DLL files from the ExternData Library folders seems to have fixed the problem.  The simulations run and I no longer get the error message.  Thank you for your help and your quick responses.

**Comment by tbeu** [comment] 2015-07-29 21:59
Glad that it works for you. But strange, I thought I checked this. I'll try to reproduce it next week with Dymola 2015 and 2016. I'll leave this issue open meanwhile.

**Comment by tbeu** [comment] 2015-08-04 07:20
Actually I cannot reproduce the problem you mentioned with Dymola 2016. I downloaded ExternData 1.0.2 from the releases, extracted it to an empty directory and opened package.mo in Dymola 2016. The example models work out of the box.

**Comment by thorade** [comment] 2015-08-04 09:31
I can confirm this issue exists. Did a fresh clone, then tried to run XMLTest1 with Dymola 2016.

![dymola_externdata](https://cloud.githubusercontent.com/assets/314571/9057709/32a7ab1c-3a9c-11e5-9299-7102f55c7b02.png)

**Comment by tbeu** [comment] 2015-08-04 09:34
@thorade Thank you for reproducing the issue. If I only would know what goes wrong here? Do you have any clue (since you are an experienced Dymola user)?

**Comment by thorade** [comment] 2015-08-04 09:38
I believe it might be related to another issue I once encountered:
https://github.com/iea-annex60/modelica-annex60/issues/40
If I manage to fix it, I will report a solution here.

**Comment by tbeu** [comment] 2015-08-04 09:45
Do you use MSVC or MinGW compiler? In my case it is MSVC.

**Comment by tbeu** [comment] 2015-08-04 09:48
In case of MSVC the linker option `/VERBOSE:Lib` displays a list of found lib dependencies.

**Comment by thorade** [comment] 2015-08-04 09:51
I tried Visual Studio 2013 Community Edition, all examples have the same error. 
The fix suggested by jnangle works: 
After deleting all dll files from `ExternData\ExternData\Resources\Library\win32` the examples simulate.
This also means that my first idea for a fix was wrong, must be something else.

Where would I specify the linker option and where can I find the output?

**Comment by tbeu** [comment] 2015-08-04 09:56
Please set `/VERBOSE:Lib` in file build.bat of your "Dymola 2016\bin" install directory. Edit line 197 from

``` bat
set LINK=%DYMOLALINK% /stack:0x500000 /NODEFAULTLIB:LIBCD /NODEFAULTLIB:LIBC /NODEFAULTLIB:LIBCMT /OPT:NOREF  %liblink% %libdsLib% %DELAYARG1% %DELAYARG2% dymosim.obj %EXTRALIB% 
```

to

``` bat
set LINK=%DYMOLALINK% /VERBOSE:Lib /stack:0x500000 /NODEFAULTLIB:LIBCD /NODEFAULTLIB:LIBC /NODEFAULTLIB:LIBCMT /OPT:NOREF  %liblink% %libdsLib% %DELAYARG1% %DELAYARG2% dymosim.obj %EXTRALIB% 
```

Please run the translation again and watch the output in the Dymola log.

**Comment by thorade** [comment] 2015-08-04 10:05
OK, I changed that line and here is the complete content from the buildlog.txt:

```
Compiling and linking the model (Visual C++). 

dsmodel.c

Searching libraries
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\user32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\advapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comdlg32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wsock32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comctl32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\netapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\dnsapi.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wininet.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shell32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\gdi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ws2_32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shlwapi.lib:
    Searching C:/Program Files (x86)/Dymola 2016\bin\lib\libds.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ole32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\OleAut32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wbemuuid.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wintrust.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\crypt32.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\delayimp.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\ED_XMLFile.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\expat.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\MSVCRT.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\OLDNAMES.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\uuid.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\kernel32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\user32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\advapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comdlg32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wsock32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comctl32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\netapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\dnsapi.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wininet.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shell32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\gdi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ws2_32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shlwapi.lib:
    Searching C:/Program Files (x86)/Dymola 2016\bin\lib\libds.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ole32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\OleAut32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wbemuuid.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wintrust.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\crypt32.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\delayimp.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\ED_XMLFile.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\expat.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\MSVCRT.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\OLDNAMES.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\uuid.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\kernel32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\user32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\advapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comdlg32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wsock32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comctl32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\netapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\dnsapi.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wininet.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shell32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\gdi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ws2_32.lib:

Finished searching libraries
   Creating library dymosim.lib and object dymosim.exp

Searching libraries
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\user32.lib:

Finished searching libraries

Searching libraries
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\user32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\advapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comdlg32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wsock32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\comctl32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\netapi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\dnsapi.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\wininet.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shell32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\gdi32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ws2_32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\shlwapi.lib:
    Searching C:/Program Files (x86)/Dymola 2016\bin\lib\libds.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\ole32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\OleAut32.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wbemuuid.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\Wintrust.lib:
    Searching C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86\crypt32.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\delayimp.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\ED_XMLFile.lib:
    Searching C:/Users/mthorade/Documents/Dymola/ExternData/ExternData/Resources/Library/win32\expat.lib:
    Searching C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\MSVCRT.lib:

Finished searching libraries
LINK : warning LNK4199: /DELAYLOAD:ED_XMLFile.dll ignored; no imports found from ED_XMLFile.dll

Successful generation of Dymosim. 

```

**Comment by tbeu** [comment] 2015-08-04 10:10
Thanks. Looks OK though since ED_XMLFile.lib and expat.lib are linked as expected.

Need to check the linker warning about the imports. Oops!! This is the problem: ED_XMLFile.dll must not be there.

**Comment by thorade** [comment] 2015-08-04 10:14
OK, I will do that.
As deleting the dlls from the `Resources\Library\win32` directory seems to fix the problem, I would assume they are the problematic part!? Are they needed or would it be an option to deliver the library without dlls?

**Comment by tbeu** [comment] 2015-08-04 10:17
Yes, indeed. The link instruction (line 197 of build.bat) contains this `DELAYLOAD:` option. Since ED_XMLFile.dll and ED_XMLFile.lib have the same name this leads to the conflict.

The reason why there are both ED_XMLFile.dll and ED_XMLFile.lib in Resources\win32 is simple. This way the lib should work out-of-the-shelf with SimulationX and Dymola (on Win). SimulationX requires the DLL only and Dymola the LIB.

**Comment by tbeu** [comment] 2015-08-04 10:18
I'll rename ED_XMLFile.dll to ITI_ED_XMLFile.dll and will release a new version soon.

**Comment by thorade** [comment] 2015-08-04 10:21
Dependecy Walker gives following warning for dymosim.exe:

```
Warning: At least one delay-load dependency module was not found.
Warning: At least one module has an unresolved import due to a missing export function in a delay-load dependent module.
```

But I did not yet find which module it is.

**Comment by tbeu** [comment] 2015-08-04 10:47
@thorade Can you please git clone again (to a new directory) and check simulation with Dymola again. Should be fixed by 26754cb.

**Comment by thorade** [comment] 2015-08-04 10:54
Yes, now it works out of the box!

**Comment by tbeu** [comment] 2015-08-04 10:54
Thanks.

**Closed as completed by tbeu** 2015-08-04 10:54 UTC

**Comment by thorade** [comment] 2015-08-04 10:56
Thanks!
I might be using the JSON reader in the future.

**Comment by tbeu** [comment] 2015-08-04 11:02
Sure. Tell me if you see improvement.

**Comment by tbeu** [comment] 2015-09-10 08:29
Argh, commit links should go to #3.
