### ISSUE TITLE
Failure using getRealArray1D from an element with many sub elements

### ISSUE THREAD

**Issue by jamesegolding** [modelica-3rdparty/ExternData#26] opened 2018-04-12 09:19 UTC
Hi tbeu,

I have an issue whereby, if an element contains more than a certain number of sub elements, any call to retrieve an array will fail.

Attached are two xmls, which are simple extensions of the example released with ExternData.
The script contains one call to getRealArray1D and works when using the "test.xml" but fails when pointing to the "testFAIL.xml", which simply contains one additional element.

Calling other values from both xmls work fine, so it seems to be the method itself rather than the parsing.

Could you check to see if you see the same problem? Is what I've done fair?
Please let me know if anything is unclear.

Many thanks!

James

I'm using:
Dymola
Visual Studio 2015 Express Edition
ExternData v2.3.3

[TestXMLs.zip](https://github.com/tbeu/ExternData/files/1902222/TestXMLs.zip)

**Comment by tbeu** [comment] 2018-04-13 06:08
I debugged and reported the upstream issue https://github.com/bsapundzhiev/bsxml-json/issues/25.

**Comment by tbeu** [comment] 2018-04-13 20:00
Resolved by v2.3.4.

**Closed as completed by tbeu** 2018-04-13 20:00 UTC
Labels: bug

**Comment by jamesegolding** [comment] 2018-04-13 21:03
That was quick, thank you! Works fine now
Thanks again
James

**Comment by jamesegolding** [comment] 2018-04-16 11:47
Sorry tbeu, it appears to me that in version 2.3.4, if the elements of an xml are not in alphabetical order, the get functions cannot find the values in the file.

You can see this in "test.xml" by moving the entire "set2" element in front of the "set1" element and running the example.
Do you see the same issue?

Thanks,
James

**Comment by tbeu** [comment] 2018-04-16 12:38
Hm, cannot reproduce. Still gives a={0.1, 0.3} even if `dummyRoot/set2` appears first in the XML file.

**Comment by jamesegolding** [comment] 2018-04-16 12:56
Sorry, I meant in the standard "XMLTest" example released with ExternData, which retrieves "set1.gain.k" and "set2.gain.k" from "test.xml".

Let me know if you still don't see it, perhaps it's an issue on my end.

Many thanks,

James

I attach the test.xml and simulation error.
[TestXMLs.zip](https://github.com/tbeu/ExternData/files/1915309/TestXMLs.zip)

**Comment by tbeu** [comment] 2018-04-16 19:23
Oops, I commited a debug change by mistake. It is all fixed (forced push) by 3e63f6542514e084091b1d854f8a0e430a6e40c0 and re-released v2.3.4.
